Junior/crud maintenance types
INF370Development/PropNoteCode-Team31 pull request #70
Opened 2023-09-21 13:58 UTC by JuniorMafolo

**Description**

Description below:

**Task of what was completed**

Work Completed below:

**Testing Steps**
1. Api Runs

2. Angular Builds

**Notes**

Notes below:

2023-09-21 14:23 UTC, u19046333 requested changes
Hey, Looks great ! please just go to where I commented and uncomment that JWT token stuff and then your PR should go through. Can't wait to see the front end :)

2023-09-21 14:23 UTC, u19046333 commented on Angular/src/app/app.module.ts
> +    /*JwtModule.forRoot({
Please uncomment this

2023-09-25 07:35 UTC, KeagandeCastro approved these changes

2023-09-25 07:35 UTC, u19046333 approved these changes

2023-09-25 07:36 UTC, merged